name: Deploy to PROD

on:
  push:
    branches:
      - main
      - github_actions
  workflow_dispatch:

env:
  # secrets.ARTIFACTORY_NPM_TOKEN comes from the "globalcommerce" org
  TRANSIENT_TOKEN: ${{ secrets.TRANSIENT_TOKEN }}
  # secrets.AZURE_* and secrets.API_KEY come from the "globalcommerce" org
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_NP }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_NP }}
  FASTE_TEAM_API_KEY: ${{ secrets.FASTE_TEAM_API_KEY }}
  # set INPUT_TOKEN='' workaround for action bug
  INPUT_TOKEN: ''
  MODULE_NAME: channel-quotes

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure NPM
        run: |
          npm config set //artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/:_auth $TRANSIENT_TOKEN
          npm config set registry https://registry.npmjs.org
          npm config set @finance-acs2:registry https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
          npm config set @monsantoit:registry https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
          npm config set @element:registry https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
          npm config set @supernova:registry https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
      - run: npm ci
      - run: npm install @monsantoit/spectrum-cli@^5.3.1 -g
      - run: npm run channel:quotes:build:np
      - name: Publish to NP using Spectrum
        run: spectrum faste publish --module-name $MODULE_NAME --module-version stable --ci --api-key $FASTE_TEAM_API_KEY --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET
